---
title: "Differential Abundance with DESEQ2 and edgeR"
output: html_notebook
author: Jim Griffin
Date: 5/30/18
---



```{r}
library(phyloseq)
packageVersion('phyloseq')
library(edgeR)
library(DESeq2)
packageVersion('DESeq2')
library(tidyverse)
library(ggplot2)
# holyshit namespace conflicts! can use package::method but I'm hoping internally packages handle this automatically.
```

### Load Data
```{r}
# Import objects
lvl5_path = '../../Seq_data/Updated_files/biom/AA_summary_MC10_MS5000/IBP_mc10_ms5000_w_tax_L5.txt'
family_tibble = read_tsv(lvl5_path,skip = 1)

# split into taxonomy names and family count data
taxonomy_strings = family_tibble[,1]
family_counts = family_tibble[,2:210]
# Split taxonomy as separate
taxonomy_columns <- tidyr::separate(taxonomy_strings, col='OTU ID', into=c('Kingdom', 'Phylum', 'Class', 'Order', 'Family'), sep=';')

#
taxonomy_col_mat <- as.matrix(taxonomy_columns)
row.names(taxonomy_col_mat) <- as_vector(taxonomy_strings['OTU ID'])
family_count_mat <- as.data.frame(family_counts)
row.names(family_count_mat) <- as_vector(taxonomy_strings['OTU ID'])

# Import Metadata and subset to samples that passed filter
samp_data = read_tsv(file='../../Metadata/ibp_metadata_4.17.18.txt')
samp_data = dplyr::filter(samp_data, SampleID %in% colnames(family_counts))
samp_data <- as.data.frame(samp_data)
rownames(samp_data) <- samp_data[,'SampleID']
samp_data[, 'USDA_soil_series'] <- as.factor(samp_data[, 'USDA_soil_series'])

levels(samp_data[, 'USDA_soil_series'])

levels(samp_data[, 'USDA_soil_series']) <- list(Watseka="Watseka loamy fine sand", Other=c("Hoopeston fine sandy loam", "Selma loam"))

# Merge everything into a phyloseq object:
OTU = otu_table(family_count_mat, taxa_are_rows = TRUE)
TAX = tax_table(taxonomy_col_mat)
sample_map = phyloseq::sample_data(samp_data)
physeq = phyloseq(OTU, TAX, sample_data<-(sample_map))



```


physeq object should be set-up enough to do differential abundance analysis in edgeR or DESeq2
```{r}
# Calculate geometric means, among other things it essentially downweights samples with high spread:
gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

# Wrap phyloseq_to_deseq so I can look at different variables. 
phy_to_DESeq_wrapper = function(physeq, col, alpha){

	form <- as.formula( paste0(' ~ ', col) ) 
	phy_dds <- phyloseq_to_deseq2(physeq, form)
	geoMeans = apply(counts(phy_dds), 1, gm_mean)
	phy_dds = estimateSizeFactors(phy_dds, geoMeans = geoMeans)
	phy_dds = DESeq(phy_dds, fitType="local")

	res = results(phy_dds)
	res = res[order(res$padj, na.last=NA), ]
	sigtab = res[(res$padj < alpha), ]
	sigtab = cbind(as(sigtab, "data.frame"), as(tax_table(physeq)[rownames(sigtab), ], "matrix"))
	return(sigtab) }

soil_sig_dds <- phy_to_DESeq_wrapper(physeq, 'USDA_soil_series', .01)
pH_sig_dds <- phy_to_DESeq_wrapper(physeq, 'pH', .01)

# TODO:
# 1. Analyze results and maybe 
#2 . do an ensemble between edger and deseq to see if we get similar results. 
# 3. Also, silva seems to heavily emphasize unknown phyla at the 99% lvl. Maybe I can re-analyze with the 97% and see if I get anything more meaningful?
```
```{r}
# Functions:
phyloseq_to_edgeR = function(physeq, group, method="RLE", ...){
  require("edgeR")
  require("phyloseq")
  # Enforce orientation.
  if( !taxa_are_rows(physeq) ){ physeq <- t(physeq) }
  x = as(otu_table(physeq), "matrix")
  # Add one to protect against overflow, log(0) issues.
  x = x + 1
  # Check `group` argument
  if( identical(all.equal(length(group), 1), TRUE) & nsamples(physeq) > 1 ){
    # Assume that group was a sample variable name (must be categorical)
    group = get_variable(physeq, group)
  }
  # Define gene annotations (`genes`) as tax_table
  taxonomy = tax_table(physeq, errorIfNULL=FALSE)
  if( !is.null(taxonomy) ){
    taxonomy = data.frame(as(taxonomy, "matrix"))
  } 
  # Now turn into a DGEList
  y = DGEList(counts=x, group=group, genes=taxonomy, remove.zeros = TRUE, ...)
  # Calculate the normalization factors
  z = calcNormFactors(y, method=method)
  # Check for division by zero inside `calcNormFactors`
  if( !all(is.finite(z$samples$norm.factors)) ){
    stop("Something wrong with edgeR::calcNormFactors on this data,
         non-finite $norm.factors, consider changing `method` argument")
  }
  # Estimate dispersions
  return(estimateTagwiseDisp(estimateCommonDisp(z)))
}


```



Running edgeR with phyloseq:
1. remove low variance samples
```{r}
physeq_r = transform_sample_counts(physeq, function(x){x/sum(x)})
hist(log10(apply(otu_table(physeq_r), 1, var)),
     xlab="log10(variance)", breaks=50,
     main="A large fraction of OTUs have very low variance")
```
```{r}
varianceThreshold = 1e-5
keepOTUs = names(which(apply(otu_table(physeq_r), 1, var) > varianceThreshold))
physeq_hi_var = prune_taxa(keepOTUs, physeq_r)
physeq_hi_var
```

```{r}
dge = phyloseq_to_edgeR(physeq_hi_var, group="USDA_soil_series")
# Perform binary test
et = exactTest(dge)
# Extract values from test results
tt = topTags(et, n=nrow(dge$table), adjust.method="BH", sort.by="PValue")
res = tt@.Data[[1]]
alpha = 0.001
sigtab2 = res[(res$FDR < alpha), ]
sigtab2 = cbind(as(sigtab2, "data.frame"), as(tax_table(physeq_hi_var)[rownames(sigtab2), ], "matrix"))
dim(sigtab)
```

